@startuml
!define C4Component
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

Container_Boundary(springApp, "Spring Boot App") {
    Component(service, "Todo Service", "Spring Component", "Gerencia as operações de negócio.")
    Component(controller, "Todo Controller", "Spring MVC REST Controller", "Gerencia as requisições HTTP.")
    Component(repository, "Todo Repository", "Spring Data", "Interface para acesso ao banco de dados.")
    
    controller -> service : Chama
    service -> repository : Utiliza
}

@enduml